### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by guidoknoop** [selfire1/todoist-focus-mode#11]
Logging in with Todoist redirects to https://flowist.app/.netlify/functions/auth-callback?code=etc... But that gives the error ERR_CONNECTION_TIMED_OUT.

**Comment by selfire1** [comment]
Thank you for raising this! I'm looking at reworking this app in the next few weeks for better performance and stability – and as a part this issue should also be resolved. Sorry for the inconvenience, but stay tuned!

**Comment by selfire1** [comment]
Hi @guidoknoop, I have completely rewritten the app. It should work well now. Let me know if you have any issues.

**Comment by guidoknoop** [comment]
Thank you so much!
