### ISSUE TITLE
Auth fails

### ISSUE THREAD

**Issue by mstem** [selfire1/todoist-focus-mode#12]
Hi
I'm trying to sign up via Login with Todoist on your website, but the passed URL resolves as a 404 on Todoist. Any ideas? thanks!
![Uploading Screenshot 2024-06-18 at 2.33.36 PM.png…]()

**Comment by selfire1** [comment]
Hi! Thank you for bringing that bug to my attention.
This should be fixed now. Would you mind testing again at https://flowist.joschua.io ?
