### ISSUE TITLE
Sorting by "due" ignores time part of due date

### ISSUE THREAD

**Issue by mindsocket** [selfire1/todoist-focus-mode#13]
When using the `sort=due:asc` parameter the comparison uses `due.date` which doesn't contain the time part of due date. The full value appears to be in `due.datetime`. [Relevant code here](https://github.com/selfire1/todoist-focus-mode/blob/f72885f0df8a086a56099d6b459be0abf8ef6284/.eleventy.js#L66)

This issue renders sorting ineffective when working through tasks in the order they've been planned out within a day.

**Comment by selfire1** [comment]
Hi @mindsocket! Thank you for raising that issue and providing relevant code.

I've released that fix and it should be live now:

<img width="1446" alt="image" src="https://github.com/selfire1/todoist-focus-mode/assets/70809675/88035b61-a90b-4f15-bca4-7c522afbfd27">

If there is a problem, feel free to reopen and thanks again for making this app better!
