### ISSUE TITLE
Add contributing/building instructions

### ISSUE THREAD

**Issue by ronilaukkarinen** [selfire1/todoist-focus-mode#16]
I could help with tasks like #14, but I'm not very familiar with Netlify. Can you write up to README.md on how to contribute and develop, how to set up a local environment?

What I gathered we need .env (could use an .env.example for this):

```ini
TODOIST_OAUTH_CLIENT_ID=
TODOIST_OAUTH_CLIENT_SECRET=
URL=http://localhost:8888
```

And the README.md addition would be something like this:

## Development

To contribute to Flowist, follow these steps:

1. **Set up a Todoist app**: 
   - Go to [Todoist Developer Console](https://developer.todoist.com/appconsole.html) and create a new app.
   - Note down your `TODOIST_OAUTH_CLIENT_ID` and `TODOIST_OAUTH_CLIENT_SECRET`.

2. **Environment variables**:
   - Create a `.env` file in the root of your project.
   - Add the following lines, replacing the placeholders with your actual credentials:
  
     ```ini
     TODOIST_OAUTH_CLIENT_ID=
     TODOIST_OAUTH_CLIENT_SECRET=
     URL=http://localhost:8888
     ```

3. **Install Netlify CLI**:
   - Ensure you have Node.js installed.
   - Install Netlify CLI globally by running: `npm install -g netlify-cli`.

4. **Run locally**:
   - Use the Netlify CLI to serve your project locally: `netlify dev`.
   - This will start a local server and you can access your app at `http://localhost:8888`.

Is this correct? With these I get  `Cannot GET /.netlify/functions/auth-before` when trying to authenticate. Am I missing a step?

**Comment by selfire1** [comment]
Hi! Thank you so much for being willing to contribute.

The source code in this repository was actually outdated. Sorry about you spending your efforts on it! I've updated the code base, and also added details to contribute as per your recommendation.

Let me know if you're able to get the local development up and running with the updated docs!

**Comment by ronilaukkarinen** [comment]
Thanks! After [using the correct node version](https://github.com/selfire1/todoist-focus-mode/pull/17) I get the server up and running, but it instantly crashes to white page with text:

```
Error
We are sorry, something went wrong.

If you think something is broken, please report it to [the Flowist issue tracker](https://github.com/selfire1/todoist-focus-mode/issues).

Message
'undefined' is not a valid GTM-ID (/^GTM-[0-9A-Z]+$/). Did you mean 'GTM-UNDEFINED'?
Clear error
```

Can GTM be disabled in dev?

**Comment by selfire1** [comment]
Thanks for bearing with me! I pushed a commit that should remove that error.

**Comment by ronilaukkarinen** [comment]
> Thanks for bearing with me! I pushed a commit that should remove that error.

No probs! Tested the newest master, GTM error is now gone, but I noticed the envs are these:

```
NUXT_OAUTH_TODOIST_CLIENT_ID=
NUXT_OAUTH_TODOIST_CLIENT_SECRET=
```

After adding these the auth seems to work, but I have `http://localhost:3000` as **OAuth redirect URL** so it just redirects me back to http://localhost:3000/?code=my_code_is_here

I have the **Login with Todoist** after this... is there a proper callback URL and how to let the app know I'm authed? I think this final step is missing from the README.md? Please inform on how to proceed.

**Comment by ronilaukkarinen** [comment]
Any idea, @selfire1?

**Comment by selfire1** [comment]
Can you try setting your *OAuth redirect URL* to `http://localhost:3000/api/auth/todoist` (or equivalent)?

And, to clarify when you used
```
CLIENT_ID=xxx
CLIENT_SECRET=yyy
```

in your `.env`, it didn't work? 

`NUXT_OAUTH_TODOIST_CLIENT_ID` and `NUXT_OAUTH_TODOIST_CLIENT_SECRET` should only be fallbacks.

**Comment by ronilaukkarinen** [comment]
Changing the OAuth redirect URL to http://localhost:3000/api/auth/todoist helped, I had http://localhost:3000 for some reason. Thanks!

**Comment by ronilaukkarinen** [comment]
Working .env:

```dotenv
NUXT_OAUTH_TODOIST_CLIENT_ID=
NUXT_OAUTH_TODOIST_CLIENT_SECRET=
NUXT_SESSION_PASSWORD=
```
