### ISSUE TITLE
Set up directions

### ISSUE THREAD

**Issue by byoriolserra** [selfire1/todoist-focus-mode#2]
When using the app for the first time, I don't see any task and I am a bit confused about how to select a specific project / list / section to focus on. Here's a screenshot of what I see:

<img width="1194" alt="Screenshot 2022-11-25 at 12 09 03 AM" src="https://user-images.githubusercontent.com/87442357/203873057-f0f60210-ae8a-4193-b816-4fd2f72763fc.png">

A one-time pop-up explaining a bit the buttons and functionalities of the app would be great.

**Comment by michdorf** [comment]
I think this is a bug. A week ago the website showed tasks on first load, now it is empty.
I get the following error in my browser console when opening the website with and without a filter
![image](https://user-images.githubusercontent.com/9166408/203932193-79daa6c7-363f-471c-b1ed-b4ce75d715e0.png)

**Comment by selfire1** [comment]
Hi! Thanks for bringing this up. This indeed is a bug that I unwittingly introduced. I'll fix it shortly.
