### ISSUE TITLE
JSON.filter is not a function

### ISSUE THREAD

**Issue by byoriolserra** [selfire1/todoist-focus-mode#3]
When opening the app on the same Arc Browser (Chromium) I had logged in a few days ago, the following error is displayed.

<img width="1227" alt="Screenshot 2022-11-28 at 4 02 33 PM" src="https://user-images.githubusercontent.com/87442357/204310675-46230462-6571-4cc3-94be-ba130c2154aa.png">

I have logged in on Chrome, where I hadn't previously opened the app yet, and it works correctly.

**Comment by byoriolserra** [comment]
I am guessing it has to do with following line of code:
https://github.com/selfire1/todoist-focus-mode/blob/78052aee033c5c60aa3bebd3cc8de6b71b55fc51/netlify/functions/dynamic/index.js#L30

**Comment by byoriolserra** [comment]
After having reset the URL to just `https://flowist.app/`, the app behaves properly. Maybe I had favorited the tab with a specific querystring that is no longer valid.

**Comment by stacksjb** [comment]
I saved/bookmarked my URLs and got this error with them as well. After reloading the main page and logging back in again, they work.

So, I suspect this error has to do with when you try to access a filter via a logged-out state (or some sort of expired session cookie or similar) - it doesn't properly handle being logged out (it should log you back in again).

**Comment by selfire1** [comment]
Should be fixed now.
