### ISSUE TITLE
Due Date sorting is broken when mixing tasks with a due date and without one

### ISSUE THREAD

**Issue by stacksjb** [selfire1/todoist-focus-mode#5]
I have a filter for all tasks with a label that are either due, overdue, or no due date (my workflow relies heavily on this filter, so things don't show up until they are due and recurring tasks go away), for example:
@Computer & (due today | overdue | no date)

However, sorting is working inconsistently or not at all - it appears it may have something with overdue dates being sorted after those that are due today.

Sorting on due:desc, my first task is due Jan 20th, the next task I am given has no due date, and the next task is due Jan 17th
Sorting on prio:desc,due:desc, I get my P1 tasks first, but the first task I am given is due today, then the next one is due 3 days ago. From there on, sorting appears correct for P2, and then when I get to P3 tasks I again am given ones due Jan 20th before being given ones due earlier and later.

Is there possibly some sort of limit on how many tasks are returned and sorted, which might be causing the issue?

I was really hoping to use this tool but I am finding it is inconsistently returning the top item from the list.

**Comment by stacksjb** [comment]
I may have found at least part of the issue - if I sort a filter with items with only a due date, it appears sorting works correctly. Sorting appears inconsistent/broken when mixing tasks without a due date and those with.

In Todoist, sorting items by due date sorts ascending by default, with tasks without a due date below those with one.  That means you get the oldest things on top first, then the newer due dates, and then tasks with no due date.

However, it appears Flowist sorts tasks without a due date first, so if I sort ascending, I get all the items without a due date first, then those with a due date second (and due date sorting is broken). Meanwhile, sorting descending appears to work correctly (at first) but the due dates are still sorted incorrectly (once I get to them).

So, it appears that due date sorting is broken when mixing due dates and no due dates.

**Comment by selfire1** [comment]
Should be fixed now with the rewrite.
