### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by OhRobin** [selfire1/todoist-focus-mode#7]
Thank you so much for creating this!

As [I have asked here](https://www.reddit.com/r/todoist/comments/10mf4m6/todoist_to_help_you_focus_on_one_task_at_a_time/?utm_source=share&utm_medium=web2x&context=3), I've wanted to make this for a very long time. 

I use it often. Have you ever thought about creating a delete button?

**Comment by selfire1** [comment]
Glad to hear you are enjoying it! I haven't thought about a delete button. If that is something that people keep requesting, I'm happy to add it.

I'll mark this as closed for now, and might reopen if there is interest.
