### ISSUE TITLE
Add description

### ISSUE THREAD

**Issue by stacksjb** [selfire1/todoist-focus-mode#8]
Hello,
It appears Flowist doesn't show Descriptions (comments).
It would be ideal if those were returned as well

**Comment by selfire1** [comment]
Not planned. You can open the task in Todoist to view all details.

**Comment by stacksjb** [comment]
Hmm, seems to be that this defeats the purpose of viewing one single task at a time 🙃

**Comment by stacksjb** [comment]
Hmm, seems to be that that would defeat the purpose of viewing one single task at a time 🙃

**Comment by selfire1** [comment]
Fair enough! I can see how you would like all relevant information at your fingertips. I reopened the issue.

**Comment by selfire1** [comment]
Hi @stacksjb, I'm pleased to let you know that this feature shipped with Flowist 1.1:

<img width="1446" alt="Screenshot 2024-06-26 at 08 33 40" src="https://github.com/selfire1/todoist-focus-mode/assets/70809675/d737e2e6-7e80-47b2-8636-0397c5399e99">

Descriptions are now automatically included below tasks, and support all formatting options from Todoist. Thanks for providing feedback!
