### ISSUE TITLE
Remove next/back buttons

### ISSUE THREAD

**Issue by ttttcrngyblflpp** [selfire1/todoist-focus-mode#9]
Flowist was working really well for me for a bit, but now I'm scrolling through my list of tasks using the next/back buttons :cry: and stressing myself out in exactly the same way that looking at the entire TODO list does.

I think these buttons should probably not be present by default, and maybe provide a toggle to show/hide them.

**Comment by selfire1** [comment]
Hi! It took a bit but I'm pleased to let you know that this feature is live with Flowist 1.1:

<img width="1446" alt="Screenshot 2024-06-26 at 08 32 14" src="https://github.com/selfire1/todoist-focus-mode/assets/70809675/e98ce4cd-4dca-4075-b54a-1bb3b8f6907a">

In the Settings (top right wheel), you can enable "Ultrafocus mode" to hide all distractions! Thank you for providing feedback.

**Comment by ttttcrngyblflpp** [comment]
Awesome, thank you!
